export const selectMunicipio = [
    {label : "Agualulco del Mercado", value : "Agualulco del Mercado"},
    {label : "Amatitán", value : "Amatitán"},
    {label : "Ameca", value : "Ameca"},
    {label : "Atenguillo", value : "Atenguillo"},
    {label : "Cocula", value : "Cocula"},
    {label : "El Arenal", value : "El Arenal"},
    {label : "Etzatlán", value : "Etzatlán"},
    {label : "Guachinango", value : "Guachinango"},
    {label : "Hostotipaquillo", value : "Hostotipaquillo"},
    {label : "Magdalena", value : "Magdalena"},
    {label : "Mascota", value : "Mascota"},
    {label : "Mixtlán", value : "Mixtlán"},
    {label : "San Juanito Escobedo", value : "San Juanito Escobedo"},
    {label : "San Martín de Hidalgo", value : "San Martín de Hidalgo"},
    {label : "San Marcos", value : "San Marcos"},
    {label : "Talpa de Allende", value : "Talpa de Allende"},
    {label : "Tala", value : "Tala"},
    {label : "Teuchitlán", value : "Teuchitlán"},
    {label : "Tequila", value : "Tequila"},
]