export const selectCampo = [
    { label: "Administración y negocios", value: "Administración y negocios" },
    { label: "Antropología", value: "Antropología" },
    { label: "Arquitectura y urbanismo", value: "Arquitectura y urbanismo" },
    { label: "Arte y cultura", value: "Arte y cultura" },
    { label: "Biología", value: "Biología" },
    { label: "Biotecnología", value: "Biotecnología" },
    { label: "Biotecnología agrícola", value: "Biotecnología agrícola" },
    { label: "Ciencia política", value: "Ciencia política" },
    { label: "Ciencias agrarias", value: "Ciencias agrarias" },
    { label: "Ciencias de la educación", value: "Ciencias de la educación" },
    { label: "Ciencias de la tierra y del espacio", value: "Ciencias de la tierra y del espacio" },
    { label: "Ciencias de las artes y las letras", value: "Ciencias de las artes y las letras" },
    { label: "Ciencias económicas", value: "Ciencias económicas" },
    { label: "Ciencias jurídicas y derecho", value: "Ciencias jurídicas y derecho" },
    { label: "Ciencias médicas", value: "Ciencias médicas" },
    { label: "Ciencias tecnológicas", value: "Ciencias tecnológicas" },
    { label: "Ciencias de la vida", value: "Ciencias de la vida" },
    { label: "Ciencias de las artes y las letras", value: "Ciencias de las artes y las letras" },
    { label: "Ciencias de la tierra y del espacio", value: "Ciencias de la tierra y del espacio" },
    { label: "Demografía", value: "Demografía" },
    { label: "Enfermería", value: "Enfermería" },
    { label: "Estudios de género", value: "Estudios de género" },
    { label: "Estudios de género CS", value: "Estudios de género CS" },
    { label: "Formación docente", value: "Formación docente" },
    { label: "Gestión", value: "Gestión" },
    { label: "Geografía", value: "Geografía" },
    { label: "Historia CS", value: "Historia CS" },
    { label: "Historia H", value: "Historia H" },
    { label: "Ingeniería", value: "Ingeniería" },
    { label: "Investigación médica", value: "Investigación médica" },
    { label: "Lengua y literatura", value: "Lengua y literatura" },
    { label: "Literatura", value: "Literatura" },
    { label: "Matemáticas", value: "Matemáticas" },
    { label: "Medios de comunicación y comunicaciones", value: "Medios de comunicación y comunicaciones" },
    { label: "No clasificado", value: "No clasificado" },
    { label: "Pedagogía", value: "Pedagogía" },
    { label: "Pesca", value: "Pesca" },
    { label: "Psicología", value: "Psicología" },
    { label: "Química", value: "Química" },
    { label: "Salud y producción animal", value: "Salud y producción animal" },
    { label: "Sociología", value: "Sociología" },
  ];
  