export const selectDisciplina = [
  { label: "Acuacultura", value: "Acuacultura" },
  { label: "Actividad económica", value: "Actividad económica" },
  { label: "Administración pública", value: "Administración pública" },
  { label: "Administración y gestión", value: "Administración y gestión" },
  { label: "Agroquímica", value: "Agroquímica" },
  { label: "Agronomía", value: "Agronomía" },
  { label: "Antropología cultural", value: "Antropología cultural" },
  { label: "Antropología social", value: "Antropología social" },
  {
    label: "Arquitectura (Planeación regional o urbana)",
    value: "Arquitectura (Planeación regional o urbana)",
  },
  {
    label: "Arquitectura, diseño y urbanismo",
    value: "Arquitectura, diseño y urbanismo",
  },
  { label: "Arte y cultura", value: "Arte y cultura" },
  { label: "Artes", value: "Artes" },
  { label: "Biotecnología", value: "Biotecnología" },
  { label: "Biotecnología agrícola", value: "Biotecnología agrícola" },
  {
    label: "Biotecnología agrícola y biotecnología alimentaria",
    value: "Biotecnología agrícola y biotecnología alimentaria",
  },
  { label: "Biotecnología productiva", value: "Biotecnología productiva" },
  { label: "Biografías", value: "Biografías" },
  { label: "Biología", value: "Biología" },
  { label: "Biología animal (zoología)", value: "Biología animal (zoología)" },
  {
    label: "Biología de insectos (entomología)",
    value: "Biología de insectos (entomología)",
  },
  { label: "Biología de poblaciones", value: "Biología de poblaciones" },
  { label: "Biología humana", value: "Biología humana" },
  {
    label: "Biología vegetal (botánica)",
    value: "Biología vegetal (botánica)",
  },
  {
    label: "Biosistemática y manejo de recursos materiales",
    value: "Biosistemática y manejo de recursos materiales",
  },
  {
    label: "Cardiología, fisiología cardiovascular",
    value: "Cardiología, fisiología cardiovascular",
  },
  { label: "Cambio y desarrollo social", value: "Cambio y desarrollo social" },
  { label: "Ciencia forestal", value: "Ciencia forestal" },
  {
    label: "Ciencias del suelo (edafología)",
    value: "Ciencias del suelo (edafología)",
  },
  { label: "Ciencias económicas", value: "Ciencias económicas" },
  {
    label: "Ciencias jurídicas y derecho",
    value: "Ciencias jurídicas y derecho",
  },
  { label: "Ciencias médicas", value: "Ciencias médicas" },
  { label: "Ciencias políticas", value: "Ciencias políticas" },
  { label: "Ciencias sociales", value: "Ciencias sociales" },
  { label: "Climatología", value: "Climatología" },
  { label: "Computación", value: "Computación" },
  {
    label: "Conservación del patrimonio arquitectónico",
    value: "Conservación del patrimonio arquitectónico",
  },
  {
    label: "Conservación de ecosistemas",
    value: "Conservación de ecosistemas",
  },
  { label: "Contabilidad económica", value: "Contabilidad económica" },
  { label: "Cuerpo y sexualidades", value: "Cuerpo y sexualidades" },
  { label: "Demografía", value: "Demografía" },
  { label: "Demografía geográfica", value: "Demografía geográfica" },
  { label: "Derecho", value: "Derecho" },
  { label: "Derecho internacional", value: "Derecho internacional" },
  {
    label: "Derecho y legislación nacionales",
    value: "Derecho y legislación nacionales",
  },
  {
    label: "Dermatología y enfermedades de transmisión sexual",
    value: "Dermatología y enfermedades de transmisión sexual",
  },
  {
    label: "Didáctica, pedagogía y currículo",
    value: "Didáctica, pedagogía y currículo",
  },
  { label: "Diseño arquitectónico", value: "Diseño arquitectónico" },
  {
    label: "Diseño, planificación y conservación de paisajes y jardines",
    value: "Diseño, planificación y conservación de paisajes y jardines",
  },
  { label: "Ecología", value: "Ecología" },
  { label: "Educación", value: "Educación" },
  {
    label: "Enfermedades de la nutrición y endocrinología",
    value: "Enfermedades de la nutrición y endocrinología",
  },
  {
    label: "Enfermedades infecciosas, bacteriología, virología clínica",
    value: "Enfermedades infecciosas, bacteriología, virología clínica",
  },
  { label: "Enfermería", value: "Enfermería" },
  { label: "Enfermería de especialidad", value: "Enfermería de especialidad" },
  { label: "Estudios culturales", value: "Estudios culturales" },
  { label: "Estudios urbanos", value: "Estudios urbanos" },
  { label: "Etnobiología", value: "Etnobiología" },
  {
    label: "Fisiopatología, fisiología clínica general",
    value: "Fisiopatología, fisiología clínica general",
  },
  { label: "Gestión ambiental", value: "Gestión ambiental" },
  {
    label: "Gestión ambiental para la sustentabilidad",
    value: "Gestión ambiental para la sustentabilidad",
  },
  {
    label: "Gestión sustentable del agua",
    value: "Gestión sustentable del agua",
  },
  { label: "Geofísica", value: "Geofísica" },
  { label: "Geografía", value: "Geografía" },
  { label: "Geografía económica", value: "Geografía económica" },
  { label: "Geografía histórica", value: "Geografía histórica" },
  { label: "Geografía regional", value: "Geografía regional" },
  { label: "Genética vegetal", value: "Genética vegetal" },
  { label: "Gestión", value: "Gestión" },
  { label: "Grupos sociales", value: "Grupos sociales" },
  { label: "Hidrología", value: "Hidrología" },
  { label: "Aguacultura", value: "Aguacultura" },
  { label: "Historia general", value: "Historia general" },
  { label: "Historia por épocas", value: "Historia por épocas" },
  {
    label: "Historia por especialidades",
    value: "Historia por especialidades",
  },
  { label: "Historia CS", value: "Historia CS" },
  { label: "Historia H", value: "Historia H" },
  { label: "Ingeniería", value: "Ingeniería" },
  { label: "Ingeniería agrícola", value: "Ingeniería agrícola" },
  { label: "Ingeniería ambiental", value: "Ingeniería ambiental" },
  { label: "Ingeniería de sistemas", value: "Ingeniería de sistemas" },
  { label: "Ingeniería mecatrónica", value: "Ingeniería mecatrónica" },
  {
    label: "Ingeniería metalúrgica y geológica",
    value: "Ingeniería metalúrgica y geológica",
  },
  { label: "Ingeniería minera", value: "Ingeniería minera" },
  { label: "Investigación clínica", value: "Investigación clínica" },
  { label: "Limnología", value: "Limnología" },
  { label: "Literatura", value: "Literatura" },
  { label: "Literatura específica", value: "Literatura específica" },
  { label: "Matemáticas", value: "Matemáticas" },
  {
    label: "Medicina y ciencias de la salud",
    value: "Medicina y ciencias de la salud",
  },
  {
    label: "Medios de comunicación y comunicación sociocultural",
    value: "Medios de comunicación y comunicación sociocultural",
  },
  {
    label: "Medios de comunicación y comunicaciones",
    value: "Medios de comunicación y comunicaciones",
  },
  { label: "Microbiología", value: "Microbiología" },
  {
    label: "Mitigación y adaptación al cambio climático",
    value: "Mitigación y adaptación al cambio climático",
  },
  { label: "Música", value: "Música" },
  { label: "Negocios y contabilidad", value: "Negocios y contabilidad" },
  { label: "Neurología y neurocirugía", value: "Neurología y neurocirugía" },
  { label: "No clasificado", value: "No clasificado" },
  { label: "Otra", value: "Otra" },
  { label: "Otra especialidad", value: "Otra especialidad" },
  {
    label: "Otras especialidades agrarias",
    value: "Otras especialidades agrarias",
  },
  {
    label: "Otras especialidades antropológicas",
    value: "Otras especialidades antropológicas",
  },
  {
    label: "Otras especialidades demográficas",
    value: "Otras especialidades demográficas",
  },
  {
    label: "Otras especialidades económicas",
    value: "Otras especialidades económicas",
  },
  {
    label: "Otras especialidades geográficas",
    value: "Otras especialidades geográficas",
  },
  {
    label: "Otras especialidades jurídicas",
    value: "Otras especialidades jurídicas",
  },
  {
    label: "Otras especialidades psicológicas",
    value: "Otras especialidades psicológicas",
  },
  {
    label: "Otras especialidades tecnológicas",
    value: "Otras especialidades tecnológicas",
  },
  {
    label: "Otras especialidades de la biología",
    value: "Otras especialidades de la biología",
  },
  {
    label: "Otras especialidades de la tierra, espacio o entorno",
    value: "Otras especialidades de la tierra, espacio o entorno",
  },
  { label: "Otro", value: "Otro" },
  { label: "Paleontología", value: "Paleontología" },
  { label: "Parasitología", value: "Parasitología" },
  { label: "Pedagogía", value: "Pedagogía" },
  { label: "Personalidad", value: "Personalidad" },
  { label: "Pesca", value: "Pesca" },
  {
    label: "Planeación del transporte y aspectos sociales del transporte",
    value: "Planeación del transporte y aspectos sociales del transporte",
  },
  { label: "Probabilidad", value: "Probabilidad" },
  { label: "Problemas sociales", value: "Problemas sociales" },
  {
    label: "Problemas sociales o social topics",
    value: "Problemas sociales o social topics",
  },
  { label: "Producción animal", value: "Producción animal" },
  { label: "Procesos tecnológicos", value: "Procesos tecnológicos" },
  {
    label: "Psicología del niño y del adolescente",
    value: "Psicología del niño y del adolescente",
  },
  { label: "Psicología experimental", value: "Psicología experimental" },
  { label: "Química", value: "Química" },
  {
    label: "Química de recursos naturales",
    value: "Química de recursos naturales",
  },
  { label: "Química general", value: "Química general" },
  { label: "Recursos acuáticos", value: "Recursos acuáticos" },
  { label: "Salud y producción animal", value: "Salud y producción animal" },
  { label: "Seguridad hídrica", value: "Seguridad hídrica" },
  { label: "Sistemas políticos", value: "Sistemas políticos" },
  { label: "Sociología", value: "Sociología" },
  { label: "Sociología cultural", value: "Sociología cultural" },
  {
    label: "Sociología de los asentamientos humanos",
    value: "Sociología de los asentamientos humanos",
  },
  {
    label: "Tecnología GM (Genéticamente modificada)",
    value: "Tecnología GM (Genéticamente modificada)",
  },
  {
    label: "Tecnologías de las telecomunicaciones",
    value: "Tecnologías de las telecomunicaciones",
  },
  {
    label: "Teoría y métodos educativos",
    value: "Teoría y métodos educativos",
  },
  {
    label: "Teoría, análisis y crítica literarias",
    value: "Teoría, análisis y crítica literarias",
  },
  { label: "Trabajo y atención social", value: "Trabajo y atención social" },
];
