export const tipoDocumento = [
        { label: "Abstract", value: "Abstract" },
        { label: "Artículo", value: "Artículo" },
        { label: "Artículo informativo", value: "Artículo informativo" },
        { label: "Capítulo de Libro", value: "Capítulo de Libro" },
        { label: "CD", value: "CD" },
        { label: "Conferencia", value: "Conferencia" },
        { label: "Crónica", value: "Crónica" },
        { label: "Documentación técnica", value: "Documentación técnica" },
        { label: "Documento de trabajo", value: "Documento de trabajo" },
        { label: "Informe de Servicio Social", value: "Informe de Servicio Social" },
        { label: "Libro", value: "Libro" },
        { label: "Memoria de congreso", value: "Memoria de congreso" },
        { label: "Memoria del proyecto", value: "Memoria del proyecto" },
        { label: "Monografía", value: "Monografía" },
        { label: "Nota científica", value: "Nota científica" },
        { label: "Paquete didáctico", value: "Paquete didáctico" },
        { label: "Ponencia", value: "Ponencia" },
        { label: "Presentación", value: "Presentación" },
        { label: "Proyecto de Aplicación Profesional", value: "Proyecto de Aplicación Profesional" },
        { label: "Reporte", value: "Reporte" },
        { label: "Reporte técnico", value: "Reporte técnico" },
        { label: "Reseña de libro", value: "Reseña de libro" },
        { label: "Resumen de Ponencia", value: "Resumen de Ponencia" },
        { label: "Resumen de Póster", value: "Resumen de Póster" },
        { label: "Revista", value: "Revista" },
        { label: "Tesina", value: "Tesina" },
        { label: "Tesis Doctorado", value: "Tesis Doctorado" },
        { label: "Tesis especialidad", value: "Tesis especialidad" },
        { label: "Tesis Ingeniería", value: "Tesis Ingeniería" },
        { label: "Tesis Licenciatura", value: "Tesis Licenciatura" },
        { label: "Tesis Maestría", value: "Tesis Maestría" },
        { label: "Vídeograbación", value: "Vídeograbación" }      
]